service:
  name: scaleway-node8
configValidationMode: off
provider:
  name: scaleway
  runtime: node8
  # Global Environment variables - used in every functions
  env:
    test: test
  # the path to the credentials file needs to be absolute
  scwToken: <scw-token>
  scwProject: <scw-project-id>

plugins:
  - serverless-scaleway-functions

package:
  exclude:
    - .gitignore
    - .git/**

functions:
  first:
    handler: handler.handle
    # Local environment variables - used only in given function
    env:
      local: local
